[2025-06-22T18:46:04.087+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: polygon_data_pipeline.fetch_ticker_details manual__2025-06-22T18:41:01.641700+00:00 [queued]>
[2025-06-22T18:46:04.092+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: polygon_data_pipeline.fetch_ticker_details manual__2025-06-22T18:41:01.641700+00:00 [queued]>
[2025-06-22T18:46:04.093+0000] {taskinstance.py:2171} INFO - Starting attempt 2 of 3
[2025-06-22T18:46:04.101+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): fetch_ticker_details> on 2025-06-22 18:41:01.641700+00:00
[2025-06-22T18:46:04.105+0000] {standard_task_runner.py:60} INFO - Started process 631 to run task
[2025-06-22T18:46:04.107+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'polygon_data_pipeline', 'fetch_ticker_details', 'manual__2025-06-22T18:41:01.641700+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/polygon_data_pipeline.py', '--cfg-path', '/tmp/tmp_ch1xhie']
[2025-06-22T18:46:04.109+0000] {standard_task_runner.py:88} INFO - Job 11: Subtask fetch_ticker_details
[2025-06-22T18:46:04.140+0000] {task_command.py:423} INFO - Running <TaskInstance: polygon_data_pipeline.fetch_ticker_details manual__2025-06-22T18:41:01.641700+00:00 [running]> on host 4a3c7287a072
[2025-06-22T18:46:04.184+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='quant-team' AIRFLOW_CTX_DAG_ID='polygon_data_pipeline' AIRFLOW_CTX_TASK_ID='fetch_ticker_details' AIRFLOW_CTX_EXECUTION_DATE='2025-06-22T18:41:01.641700+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-22T18:41:01.641700+00:00'
[2025-06-22T18:46:04.195+0000] {polygon_data_pipeline.py:79} ERROR - Failed to get Polygon API key: 'Variable polygon_api_key does not exist'
[2025-06-22T18:46:04.195+0000] {polygon_data_pipeline.py:80} INFO - Please set up the API key using one of these methods:
[2025-06-22T18:46:04.195+0000] {polygon_data_pipeline.py:81} INFO - 1. Airflow Connection (RECOMMENDED): Admin -> Connections
[2025-06-22T18:46:04.195+0000] {polygon_data_pipeline.py:82} INFO -    - Conn Id: polygon_api
[2025-06-22T18:46:04.195+0000] {polygon_data_pipeline.py:83} INFO -    - Conn Type: HTTP
[2025-06-22T18:46:04.195+0000] {polygon_data_pipeline.py:84} INFO -    - Password: your_api_key
[2025-06-22T18:46:04.196+0000] {polygon_data_pipeline.py:85} INFO - 2. Environment Variable: POLYGON_API_KEY
[2025-06-22T18:46:04.196+0000] {polygon_data_pipeline.py:86} INFO - 3. Airflow Variable: polygon_api_key
[2025-06-22T18:46:04.196+0000] {polygon_data_pipeline.py:87} INFO - Get your free API key at: https://polygon.io/
[2025-06-22T18:46:04.196+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/polygon_data_pipeline.py", line 283, in fetch_ticker_details
    api_key = get_polygon_api_key()
              ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/polygon_data_pipeline.py", line 74, in get_polygon_api_key
    api_key = Variable.get("polygon_api_key")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable polygon_api_key does not exist'
[2025-06-22T18:46:04.203+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=polygon_data_pipeline, task_id=fetch_ticker_details, execution_date=20250622T184101, start_date=20250622T184604, end_date=20250622T184604
[2025-06-22T18:46:04.208+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 11 for task fetch_ticker_details ('Variable polygon_api_key does not exist'; 631)
[2025-06-22T18:46:04.244+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-06-22T18:46:04.255+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
